export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_SET_IS_AUTH = 'AUTH_SET_IS_AUTH';
export const AUTH_SET_IS_FETCHING = 'AUTH_SET_IS_FETCHING';
export const AUTH_SET_ERROR_MESSAGE = 'AUTH_SET_ERROR_MESSAGE';
export const AUTH_SET_INITIALIZED = 'AUTH_SET_INITIALIZED';
